# Używamy pełnego obrazu Node.js, który jest lepszy do celów deweloperskich
FROM node:20

# Ustawienie katalogu roboczego
WORKDIR /app

# Kopiujemy tylko package.json i package-lock.json, aby wykorzystać cache Dockera
COPY package*.json ./

# Instalujemy wszystkie zależności, w tym devDependencies
RUN npm install

# Uruchamiamy serwer deweloperski Vite
# Używamy --host, aby był dostępny z zewnątrz kontenera
CMD ["npm", "run", "dev", "--", "--host"]
